### ISSUE TITLE
Add support for binding to other events

### ISSUE THREAD

**Issue by mister-walter** [cevherkarakoc/Pie-Context-Menu#2]
It might be nice to be able to bind showing the menu to other events (i.e. left/middle click, or maybe even hover).

I'm willing to work on this and submit a PR if others think there's some value in this feature.

**Comment by cevherkarakoc** [comment]
This is a good idea. I am waiting for your PR.

**Comment by mister-walter** [comment]
Sorry about the wait, PR is in.
