### ISSUE TITLE
Add webpack compatibility

### ISSUE THREAD

**Issue by mister-walter** [cevherkarakoc/Pie-Context-Menu#4]
Currently, this library doesn't work with Webpack, due to the use of event attributes in the setMenuButtonG function. I think this can be rectified by replacing event attributes with addEventListener calls.

In addition, adding a UMD wrapper would eliminate the need for a shim to export the PieContextMenu variable.

**Comment by cevherkarakoc** [comment]
#6 thanks dude, you are great
