### ISSUE TITLE
Enable for touch

### ISSUE THREAD

**Issue by liveman1** [cevherkarakoc/Pie-Context-Menu#7]
Hi, 
thanks for providing this code! Just awesome!
Would it be possible to include touch events to open the context menu?
Something like: https://github.com/remziatay/circle-context-menu

Moreover it would be great to close the menu by another click with the right mouse button.

Unfortunately, I have no idea how to do that.

Best regards!
Steffen

**Comment by cevherkarakoc** [comment]
Hi,
I no longer maintain this repo. But if you can handle touch events there are helper methods to open and to close.

Example :
my_menu.openMenu() //open the menu;
my_menu.closeMenu() //close the menu;

**Comment by liveman1** [comment]
Hi,

thanks a lot for your answer.
I will look into it.

Best regards
Steffen

Cevher ***@***.***> schrieb am Mi. 8. Sept. 2021 um 13:22:
